function y = glot_int(x, g)

y = (x + (x .^ 2 + g.omega_g ^ 2)...
    / g.epsilon) * sin(g.omega_g * g.t_e)...
    - g.omega_g * cos(g.omega_g * g.t_e)...
    + g.omega_g * exp(-x * g.t_e);

% y = (x * sin(g.omega_g * g.t_e)...
%     - g.omega_g * cos(g.omega_g * g.t_e)...
%     + g.omega_g * exp(-x * g.t_e))...
%     ./ ((x .^ 2 + g.omega_g ^ 2) * -sin(g.omega_g * g.t_e))...
%     - 1 / g.epsilon;

end